version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    
    ports:
      - 8080:80
    environment:
      - PMA_HOST=tramway.proxy.rlwy.net
      - PMA_PORT=37369
      - PMA_USER=root
      - PMA_PASSWORD=HXzZaXcinNzWsiTTEGkTrEpZzBAzXYzd